#!/usr/bin/env bash
set -Eeuo pipefail
colors="--ab #2C323E --af #9899a0 --nb #2C323E --nf #9899a0 --sb #BF616A --sf #2C323E"
# search root
root_path=$HOME



prompt="-p Folder"

file_path="$(find $root_path -maxdepth 5 -type d \( ! -regex '*/\..*' \) | \
             sed 's|^'$root_path/'||' | sort | \
             bemenu -i $colors --fn "JetBrainsMono 12" -l 10 )"

if [[ ! -z $file_path ]]; then

    if [[ "$file_path" == "$root_path" ]]; then
        search_path=$root_path
    else
        search_path="$root_path/$file_path"
    fi

    total="$(find "$search_path" -maxdepth 1 -type f | wc -l)"
    
    if [[ $total -eq 0 ]]; then
        prompt="No files here!"
    else
        prompt="File:"
    fi

    file_name="$(find "$search_path" -maxdepth 1 -type f | \
                 awk -F'/' '{print $NF}' | \
                 bemenu -i $colors --fn "JetBrainsMono 12" -l 10)"

    if [[ ! -z $file_name ]]; then
       rifle "$search_path/$file_name"
    fi

fi

exit 0
