local g = vim.g
g.vimtex_view_method = 'zathura'
g.maplocalleader = ","
g.syntastic_always_populate_loc_list = 1
g.syntastic_always_populate_loc_list = 1
g.syntastic_check_on_open = 1   
g.syntastic_check_on_wq = 0
g.syntastic_tex_checkers = 'lacheck'
g.vimtex_syntax_enabled = 0
g.vimtex_syntax_conceal_disable = 1
